{{- if and .Values.tunneld.config.enabled (not .Values.tunneld.existingSecret.enabled) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tunneld.name" . }}-secret
  labels:
    {{- include "tunneld.labels" . | nindent 8 }}
type: Opaque
data:
  config.yaml: {{ .Values.tunneld.config.values | b64enc | quote }}
{{- end }}