{{- if and .Values.tunneld.config.enabled (not .Values.tunneld.existingSecret.enabled) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tunneld.name" . }}-secret
  labels:
    app.kubernetes.io/name: {{ include "tunneld.name" . }}
    helm.sh/chart: {{ include "tunneld.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  config.yaml: {{ .Values.tunneld.config.values | b64enc | quote }}
{{- end }}